platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 2.0.0'
pod 'Parse-iOS-SDK', '~> 1.2.18'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'DropdownMenu', '~> 1.0.0'
pod 'BZGFormViewController', '~> 1.0.1'
pod 'BZGMailgunEmailValidation', '~>1.1.0'
pod 'M13ProgressSuite', '~> 1.0.0'
pod 'FRDLivelyButton'
pod 'AFNetworking', '~> 2.0'
pod 'MMProgressHUD', '~> 0.2.2'
pod 'PopoverView'
pod 'TestFlightSDK', '~> 3.0.0'
pod 'Shimmer', '~> 1.0.1' 
